# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.6

script :
  -python3 test.py


# Install the codecov pip dependency
#install:
#  - pip install codecov


# Run the unit test

#script:
 # - coverage run test.py

# Push the results back to codecov
#after_success:
 # - codecov